version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5


jobs:
  ubuntu-job:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: echo "hello"

  security-scan:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: echo "I got this far, amazing!"
      #- run: exit 1

workflows:
  demo-workflow:
    jobs:
      #- security-scan
      - ubuntu-job
