version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0


jobs:
  ubuntu-job:
    machine:
      image: ubuntu-2404:current
    steps:
      - run: echo "hello"

  security-scan:
    machine:
      image: ubuntu-2204:current
    steps:
      - run: echo "I got this far, amazing!"
      - run: exit 1

workflows:
  demo-workflow:
    jobs:
      - security-scan
      - ubuntu-job
