version: 2.1

jobs:
  ubuntu-job:
    machine: true
    steps:
      - run: echo "hello"

  security-scan:
    machine: true
    steps:
      - run: echo "I got this far, amazing!"

workflows:
  demo-workflow:
    jobs:
      - security-scan
      - ubuntu-job